### ISSUE TITLE
block_test tests fail on Mac OSX Yosemite

### ISSUE THREAD

**Issue by ruhatch** [mirage/mirage-skeleton#103]
Following the Hello MirageOS Guide, the block_test example fails the tests with the following trace:

```
sectors = 100000
read_write=true
sector_size=512
writing 1 sectors at 0
writing 1 sectors at 99999
writing 2 sectors at 0
writing 2 sectors at 99998
writing 12 sectors at 0
writing 12 sectors at 99988
writing 1 sectors at 100000
-- expected failure; got success
writing 12 sectors at 99989
-- expected failure; got success
reading 1 sectors at 100000
-- expected failure; got success
reading 12 sectors at 99989
-- expected failure; got success
Test sequence finished
Total tests started: 10
Total tests passed:  6
Total tests failed:  4
```
So sectors are being written that are meant to be out-of-bounds. On running the command again we get `sectors = 100001`, so a sector has been added to the disk image as expected. I'm not sure that this is much of an issue, but it would be good if the tests were adapted to work in this environment.

**Comment by talex5** [comment]
The way to track this down is to git clone [mirage-block-unix](https://github.com/mirage/mirage-block-unix) and add some debug / read the code. If you're willing to give it a try, it would probably make a nice starter project!

(use `opam pin` to test with your modified version)

**Comment by ruhatch** [comment]
I spent some time debugging this and reading through the code.

From what I can see there isn't actually a reason for the IO operations to fail, at least in the order they are currently defined. The write operation eventually drops through to C's `write()`, which will continue to write past an EOF symbol, so the write operation completes successfully. Then the read is also successful because it occurs after the write. If you move the `check_sector_read_failure` test to before the `check_sector_write_failure` test, then it will pass, because it will reach an EOF in this instance.

What I'm interested to know is whether these tests work for you and, if so, where does the code stop the write operation from writing past the end of the file? Maybe it is platform specific behaviour of the C function, in which case we should implement something higher up that makes sure it is consistent. What semantics do you really want from a block device? Should it be able to expand on write?

**Comment by talex5** [comment]
I ran it myself and saw the same messages. However, it returns success even on failure, e.g.:

    $ ./main.native && echo OK
    ...
    Test sequence finished
    Total tests started: 10
    Total tests passed:  6
    Total tests failed:  4
    OK

I think mirage-skeleton should be modified to raise an exception at the end if there were failures. Then the automatic tests would pick this up. Patches welcome!

**Comment by ruhatch** [comment]
It turns out that there's a pull request from July that fixes this problem!

https://github.com/mirage/mirage-block-unix/pull/32

**Comment by djs55** [comment]
The mirage-block-unix fix has been merged and released. A fresh checkout of d2500bf633206a88bac6c72b2ac2864341ff1f60 with mirage 2.7.0 works fine:

```
$ ./mir-block_test
sectors = 100000
read_write=true
sector_size=512
writing 1 sectors at 0
writing 1 sectors at 99999
writing 2 sectors at 0
writing 2 sectors at 99998
writing 12 sectors at 0
writing 12 sectors at 99988
writing 1 sectors at 100000
writing 12 sectors at 99989
reading 1 sectors at 100000
reading 12 sectors at 99989
Test sequence finished
Total tests started: 10
Total tests passed:  10
Total tests failed:  0
```
Re-open if you see the problem again!
