### ISSUE TITLE
ld: error in _build/main.native.o(.eh_frame)

### ISSUE THREAD

**Issue by seriousme** [mirage/mirage-skeleton#106]
Hi,

I've been building the static_website demo following the instructions on http://www.skjegstad.com/blog/2015/01/19/mirageos-xen-virtualbox/

At the end of the make in  mirage-skeleton/static_website I get an error: 
```
ld: error in _build/main.native.o(.eh_frame); no .eh_frame_hdr table will be created.
```
The resulting unikernel runs fine on Xen (i.e. I can connect to the webserver) but you might want to fix it.

Kind regards,
Hans

**Comment by MagnusS** [comment]
This error message is always shown when buildling Xen unikernels. It was also reported here last year: https://github.com/mirage/mirage/issues/258. It is harmless, but unfortunately looks like a fatal error as it's the last line in the `make` output.

**Comment by seriousme** [comment]
Thanks for the explanation, would it be an idea to have the makefile for Xen emit a last line saying something like:
"if the next line says 'no .eh_frame_hdr table will be created.' it can be safely ignored"  ?

**Comment by seriousme** [comment]
That works as well :-)
