### ISSUE TITLE
Block example not working with Xen 4.6

### ISSUE THREAD

**Issue by olivierpierre** [mirage/mirage-skeleton#114]
Hello,

The example in the `block` folder is not working for me with Xen stable-4.6 (Ubuntu 14.04 x86_64). The Unix version is working fine.

Building the unikernel seems to be working fine, the problem is at runtime. It seems to be related to the virtual disk.

For the Xen guest version, here is how I get the error:

```shell
$ cd block
$ ./generate_disk_img.sh
$ mirage configure --xen
$ make
$ sudo xl create block_test.xl -c
Parsing config from block_test.xl
libxl: error: libxl_device.c:283:libxl__device_disk_set_backend: Disk vdev=xvdc failed to stat: /home/pierre/mirage-skeleton/block/xvda1: No such file or directory
libxl: error: libxl_create.c:906:initiate_domain_create: Unable to set disk defaults for disk 1
libxl: error: libxl.c:1591:libxl__destroy_domid: non-existant domain 7
libxl: error: libxl.c:1549:domain_destroy_callback: unable to destroy guest with domid 7
libxl: error: libxl.c:1476:domain_destroy_cb: destruction of domain 7 failed
```

I was able to fix the problem by changing [`config.ml`](https://github.com/mirage/mirage-skeleton/blob/master/block/config.ml) to:
```ocaml
open Mirage

let main = foreign "Unikernel.Main" (console @-> block @-> job)

let img =
  if_impl Key.is_xen
    (block_of_file "disk.img") (*The change is here, replaced "xvda1" by "disk.img" *)
    (block_of_file "disk.img")

let () =
  register "block_test" [main $ default_console $ img]
```

With that modification the Xen guest start and the read / write tests are successful.

**Comment by talex5** [comment]
Confirmed. Looks like a bug in the Mirage tool, which I've reported here:

https://github.com/mirage/mirage/issues/504

**Comment by jboothapati** [comment]
libxl: error: libxl.c:434:libxl__domain_rename: domain with name "host" already exists.
libxl: error: libxl_create.c:881:initiate_domain_create: cannot make domain: -6
libxl: error: libxl.c:1591:libxl__destroy_domid: non-existant domain 86
libxl: error: libxl.c:1549:domain_destroy_callback: unable to destroy guest with domid 86
libxl: error: libxl.c:1476:domain_destroy_cb: destruction of domain 86 failed

**Comment by jboothapati** [comment]
Can  you help on this issue

**Comment by jboothapati** [comment]
I dont have password to login it again with the command xl console <Host>

**Comment by mor1** [comment]
@jboothapati Hi-- what are you actually trying to do? It would be better to open a new issue unless your problem is the same as the one report at the top of this issue. This issue is resolved.

(FWIW the first line you report looks to me like you're trying create a domain with the same name as one that already exists. But it's a bit hard to tell without more context.)
