### ISSUE TITLE
static_website_tls: certificate issue at runtime

### ISSUE THREAD

**Issue by azul** [mirage/mirage-skeleton#119]
I'm not sure how the certificate handling in the static_website_tls example is supposed to work. Currently it fails for me with:
```
Fatal error: exception Invalid_argument("Tls.Config: invalid configuration: certificate type or usage does not match")
Raised at file "pervasives.ml", line 21, characters 25-45
Called from file "lib/config.ml", line 94, characters 18-75
Called from file "lib/config.ml", line 241, characters 29-51
Called from file "dispatch.ml", line 53, characters 20-40
Called from file "main.ml", line 130, characters 2-51
Called from file "src/core/lwt.ml", line 653, characters 66-69
Re-raised at file "src/core/lwt.ml", line 789, characters 22-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "main.ml", line 151, characters 5-10
```

I'd be happy about a clue where it expects the certs and would create a pull request to include it in the documentation.

**Comment by azul** [comment]
I'm also looking into a way to test these things as part of the travis run. It would be nice if it started all the servers and checked that they actually start.

**Comment by samoht** [comment]
I'm not sure this examples is kept very up-to-date. Please see [mirage-seal](https://github.com/mirage/mirage-seal) for a more real example

**Comment by azul** [comment]
@samoht , thanks. I think then it should either be removed or updated. Misleading examples are worth than missing ones ;).

I wrote a little bash script to test if the created executable actually runs:
```bash
./mir-www &
sleep 1
kill $!
```
kill will succeed only if the process is still running after 1 second. So something like this could be used to test on the CI if all the examples also run and not just compile.

Would you be interested in including something like this? Then i would prepare a pull request.

**Comment by Drup** [comment]
@azul Yes, that would be very nice. 

@samoht I just noticed that seal is not updated for functoria :(

**Comment by azul** [comment]
#120 would be my take.

**Comment by azul** [comment]
#121 runs all the executables on travis. Others are failing too.

**Comment by azul** [comment]
This issue is mostly about the broken former static_website_tls. This is now fixed. The integration testing for travis is a different issue and tracked by the corresponding pull request #121 
So I will close this..
