### ISSUE TITLE
Configure should be configurable for xen/unix

### ISSUE THREAD

**Issue by fxfactorial** [mirage/mirage-skeleton#129]
Thank you for these great samples.

I was using the console example and it by default uses mirage-configure --unix, is there a clean way to do --xen via the build system rather than doing it by hand?

**Comment by samoht** [comment]
`make configure MODE=xen` at the root of the repo will configure all the examples with the Xen mode.

**Comment by fxfactorial** [comment]
thanks!

**Comment by samoht** [comment]
You can also tweak the `MIRAGE_FLAGS` flags to add `--no-depext` and `--no-opam` to speed up the process if you already have all the needed opam packages already installed.
