### ISSUE TITLE
Example from README: mirage: unknown option --unix

### ISSUE THREAD

**Issue by lindig** [mirage/mirage-skeleton#131]
After installing mirage 2.7.3 from OPAM on a Debian X86, examples given in the README result in:

    :mirage-skeleton $ make sample-configure
    mirage configure -f sample/config.ml --unix 
    mirage: unknown option `--unix'.
    Usage: mirage configure [OPTION]... 
    Try `mirage configure --help' or `mirage --help' for more information.
    Makefile:41: recipe for target 'sample-configure' failed
    make: *** [sample-configure] Error 1

I also noticed that there is no file `sample/config.ml` file. Maybe sample refers to `hello` and so on but this isn't obvious. At this point I have no idea how to go on.

**Comment by lindig** [comment]
I now realise that `make sample-configure` really means something like `make hello-configure`. This isn't obvious. So this is mostly a documentation problem.

**Comment by djs55** [comment]
I agree this is confusing. I think we should change the README so people can simply cut and paste the command-lines into their terminals. Perhaps we should use the "hello" example in the README.
