### ISSUE TITLE
dhcp updates

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-skeleton#136]
in @haesbaert tree there are some commits which would be nice to have in master:
- https://github.com/haesbaert/mirage-skeleton/commit/c83783aa7b93b082d2515f30ef7554ad775f1c5e
- https://github.com/haesbaert/mirage-skeleton/commit/584c99613c6b605820151ea1d3f64dd784eb1e7f
- https://github.com/haesbaert/mirage-skeleton/commit/c32c3f6bfdc9d5f68d81a1d886d9caafe1969c64
- https://github.com/haesbaert/mirage-skeleton/commit/5b0ca9d2f307c81cc7e4b221bb987eecc9032e7b
- https://github.com/haesbaert/mirage-skeleton/commit/8f994cf884c45db94891b46c8ecb69c52a659d95
- https://github.com/haesbaert/mirage-skeleton/commit/646a4c562690d9a365546abc091a43071504138c

**Comment by haesbaert** [comment]
This can be closed as those commits were integrated in 437cefcc11d72ffc0c3afc0cc80c20deb71e7e1d
