### ISSUE TITLE
DNS example fails with the socket network target

### ISSUE THREAD

**Issue by zorun** [mirage/mirage-skeleton#159]
When building the DNS example with the socket network target, like this:

```
$ mirage configure -f dns/config.ml --unix --net socket
$ make -C dns
```

the program fails at runtime:

```
# ./dns/mir-dns 
Manager: connect
Manager: configuring
2016-07-13 14:07.49: INF [client] Starting client resolver
Fatal error: exception Unix.Unix_error(Unix.EUNKNOWNERR 126, "send", "")
Raised by primitive operation at file "src/unix/lwt_bytes.ml", line 215, characters 37-92
Called from file "src/unix/lwt_unix.ml", line 549, characters 17-28
```

It works fine when compiled to work with a tap interface (`mirage configure --unix --net direct`).

**Comment by yomimono** [comment]
I should've asked this yesterday, but can you describe the system you're running this on?  OS, distro, version?

**Comment by zorun** [comment]
So, it turns out that I was routing 8.8.8.8 to an experimental VPN interface, which caused Mirage to fail to send packets.

Thus, it's "just" a robustness issue, not really a bug.  It's possible to achieve similar failures with unreachable and blackhole routes:

```ip route add unreachable 8.8.8.8/32```

```
2016-07-14 21:47.31: INF [client] Starting client resolver
Fatal error: exception Unix.Unix_error(Unix.EHOSTUNREACH, "send", "")
Raised by primitive operation at file "src/unix/lwt_bytes.ml", line 215, characters 37-92
Called from file "src/unix/lwt_unix.ml", line 549, characters 17-28
```

```ip route replace blackhole 8.8.8.8/32```

```
2016-07-14 21:47.45: INF [client] Starting client resolver
Fatal error: exception Unix.Unix_error(Unix.EINVAL, "send", "")
Raised by primitive operation at file "src/unix/lwt_bytes.ml", line 215, characters 37-92
Called from file "src/unix/lwt_unix.ml", line 549, characters 17-28
```
