### ISSUE TITLE
The path to htdocs seems to be wrong when configured for unix

### ISSUE THREAD

**Issue by crowdwave** [mirage/mirage-skeleton#204]
When configuring for unix, the main.ml seems to end up with an absolute path to the htdocs location.

This means that if you move the unikernel to a different machine then it will not work - cannot find the htdocs, because that absolute path does not exist.

To make it work, I have to modify main.ml from:

`Kvro_fs_unix.connect "/home/ubuntu/mirage-skeleton/static_website/htdocs"`

to:

`Kvro_fs_unix.connect "./htdocs"`

and then have the htdocs directory in the current directory that the unikernel is run from, and it seems to work.

**Comment by yomimono** [comment]
I believe this was resolved in Mirage 3.0.0 and should have been closed then.  Sorry for the (very!) belated response, @crowdwave !
