### ISSUE TITLE
kv_ro examples not working when passed --kv_ro=archive

### ISSUE THREAD

**Issue by johannesfrey** [mirage/mirage-skeleton#230]
When executing make I get following error:

```
ocamlfind: Package `tar.mirage' not found
ocamlfind ocamldep -package tar.mirage -package mirage-unix -package mirage-types-lwt -package mirage-types -package mirage-runtime -package mirage-
logs -package mirage-clock-unix -package mirage-block-unix -package lwt -package functoria-runtime -predicates mirage_unix -modules main.ml > main.m
l.depends
+ ocamlfind ocamldep -package tar.mirage -package mirage-unix -package mirage-types-lwt -package mirage-types -package mirage-runtime -package mirag
e-logs -package mirage-clock-unix -package mirage-block-unix -package lwt -package functoria-runtime -predicates mirage_unix -modules main.ml > main
.ml.depends
ocamlfind: Package `tar.mirage' not found
Command exited with code 2.
run ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tags'
     'predicate(mirage_unix),warn(A-4-41-42-44),debug,bin_annot,strict_sequence,principal,safe_string,color(always)'
     '-pkgs'
     'functoria-runtime,lwt,mirage-block-unix,mirage-clock-unix,mirage-logs,mirage-runtime,mirage-types,mirage-types-lwt,mirage-unix,tar.mirage'
     '-cflags' '-g' '-lflags' '-g' '-tag-line' '<static*.*>: warn(-32-34)'
     '-X' '_build-ukvm' 'main.native']: exited with 10
Makefile:18: recipe for target 'build' failed
make: *** [build] Error 1
```
I then rather naively emptied the list for ~ocamlfind here: [https://github.com/mirage/mirage/blob/188aa887cc8707c39472af58acf5a85ad8dbed54/lib/mirage.ml#L424](https://github.com/mirage/mirage/blob/188aa887cc8707c39472af58acf5a85ad8dbed54/lib/mirage.ml#L424)

which leads to another error:

```
File "main.ml", line 10, characters 21-42:
Error: Unbound module Tar_mirage
Command exited with code 2.
run ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tags'
     'predicate(mirage_unix),warn(A-4-41-42-44),debug,bin_annot,strict_sequence,principal,safe_string,color(always)'
     '-pkgs'
     'functoria-runtime,lwt,mirage-block-unix,mirage-clock-unix,mirage-logs,mirage-runtime,mirage-types,mirage-types-lwt,mirage-unix'
     '-cflags' '-g' '-lflags' '-g' '-tag-line' '<static*.*>: warn(-32-34)'
     '-X' '_build-ukvm' 'main.native']: exited with 10
Makefile:18: recipe for target 'build' failed
make: *** [build] Error 1
```

Just started playing around with the mirage examples so I'm not sure if I'm missing some specifics for the Archive key here. Also I'm not sure if the main repo for mirage would be more appropriate for the issue. If requested I can open up the issue there of course.

**Comment by yomimono** [comment]
Thanks for the report, @johannesfrey .  Did you execute `make depend` between `mirage configure` and `make`?

**Comment by johannesfrey** [comment]
@yomimono yep I ran `mirage configure -t unix --kv_ro=archive; make depend; make`

I also tried it for xen and macosx targets, leading to the same error.
Btw. I'm running following versions:
opam 1.2.2, ocaml 4.04.0 and mirage 3.0.2.
Mac OSX 10.11.6, Ubuntu 16.04.2, Xen 4.6.5

**Comment by olleolleolle** [comment]
I ran that command (thank you for including it in your report!) and had no error output.

- opam 1.2.2, ocaml 4.05.0, mirage 3.0.5
- macOS 10.12.6

Can this issue be closed?

**Comment by hannesm** [comment]
thanks @olleolleolle -- some more investigation turns that since mirage 3.0.5 the constraint for tar was adjusted (to tar-mirage) in https://github.com/mirage/mirage/commit/f726f13a0d025494933b9b05c411d4924ef5d830h

@johannesfrey could you please update your mirage to 3.0.5 and reopen in case the issue persists?
