### ISSUE TITLE
ocamlfind: Package `conduit.mirage' not found

### ISSUE THREAD

**Issue by thwg** [mirage/mirage-skeleton#232]
When trying to build the static_website_tls example, with a clean 4.04.2 switch and mirage 3.0.2:

```
mirage configure -t unix
make depend
make
```

I receive the error:

```
+ ocamlfind ocamldep -package uri -package tls.mirage -package tls -package tcpip.udp -package tcpip.tcp -package tcpip.stack-direct -package tcpip.ipv4 -package tcpip.icmpv4 -package tcpip.ethif -package tcpip.arpv4 -package tcpip -package nocrypto.lwt -package nocrypto -package mirage-unix -package mirage-types-lwt -package mirage-types -package mirage-runtime -package mirage-random -package mirage-net-unix -package mirage-logs -package mirage-kv-lwt -package mirage-http -package mirage-flow-lwt -package mirage-clock-unix -package mirage-clock -package magic-mime -package lwt -package io-page.unix -package io-page -package functoria-runtime -package conduit.mirage -package conduit -predicates mirage_unix -modules main.ml > main.ml.depends
ocamlfind: Package `conduit.mirage' not found
```

It appears that the package names [have been changed in mirage-conduit 3.0.x](https://github.com/mirage/ocaml-conduit/releases/tag/v1.0.0):

> In each of these packages, the opam and ocamlfind package
> names are now the same, so you will need to rename the former
> subpackages such as conduit.async to conduit-async. The
> implementation is otherwise the same, so no other code changes
> should be required.

The generated `mirage-unikernel-https-unix.opam` contains the dependency `"mirage-conduit" {>="2.3.0"}`.

My version is 3.0.1:

```
mirage-conduit  3.0.1  Network conduit library
```

(Sorry if this is the wrong tracker. I'm not quite sure how the package names / versions are being generated; it seems the `mirage configure/build` commands are automatically determining them somehow, as I'm not manually configuring them and don't see any settings I can change in the skeleton project).

**Comment by hannesm** [comment]
The dependencies are indeed generated by `mirage configure`.  For a temporary fix you can `opam pin add mirage-conduit 2.3.1`.

**Comment by twopoint718** [comment]
I'm getting a dependency error related to this package while working with:

- opam 1.2.2
- ocaml 4.05.0

```
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following dependencies couldn't be met:
  - mirage-conduit -> conduit < 0.16.0 -> sexplib < 113.24.00
  - mirage-conduit -> conduit < 0.16.0 -> ppx_deriving
  - mirage-conduit -> conduit < 0.16.0 -> pa_sexp_conv < v0.9.0
  - mirage-conduit -> conduit < 0.16.0 -> ipaddr < 2.8.0 -> ppx_deriving
Your request can't be satisfied:
  - pa_sexp_conv<v0.9.0 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".
  - ppx_deriving is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.05" & opam-version >= "1.2".
  - sexplib<113.01.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".
  - sexplib<113.24.00 is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.03".

No solution found, exiting
```

When doing a `make depend` I end up hitting:

```
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[mirage-unikernel-https-unix] /Users/chris/code/mirage-skeleton/applications/static_website_tls/ already up-to-date
The following dependencies couldn't be met:
  - mirage-unikernel-https-unix -> nocrypto >= 0.5.4 -> ppx_deriving
Your request can't be satisfied:
  - ppx_deriving is not available because your system doesn't comply with ocaml-version >= "4.02.1" & ocaml-version < "4.05" & opam-version >= "1.2".

No solution found, exiting
make: *** [depend] Error 3
```

Is my OCaml version too new for `ppx_deriving`?

Thanks!

**Comment by hannesm** [comment]
Thanks for your reports, since mirage 3.0.5 and tcpip 3.3.0 these issues should be solved.  Please report if the problem persists after `opam update` and `opam upgrade`.  Thanks!

**Comment by twopoint718** [comment]
@hannesm Thanks!
