### ISSUE TITLE
Networking relented example fails to run (unix & ukvm)

### ISSUE THREAD

**Issue by ciarancourtney** [mirage/mirage-skeleton#234]
Both the conduit and static website examples fail to boot for me, I tried unix and ukvm, the output respectively:

```
2017-08-15 21:40:55 +01:00: ERR [application] main: (Failure "tun[TUNSETIFF]: Operation not permitted")
Raised by primitive operation at file "lib/tuntap.ml", line 34, characters 2-53
Called from file "src/netif.ml", line 61, characters 22-58
```

```
ukvm-bin: Module `net' setup failed
ukvm-bin: Please check you have correctly specified:
    --net=TAP (host tap device for guest network interface or @NN tap fd)
    [ --net-mac=HWADDR ] (guest MAC address)

```

I'm running this on Ubuntu 16.04 on VMware VM, the hello example runs fine.

**Comment by ciarancourtney** [comment]
Using `mirage configure -t unix --net socket` as per the Hello World tutorial on mirage.io resolves the issue for the unix case

**Comment by hannesm** [comment]
hey, in your error message your Linux complains about `Operation not permitted` while setting up the tap interface. you may want to execute `ukvm-bin` as superuser (e.g. with `sudo ./ukvm-bin --net=tapX <kernel>`.

**Comment by ciarancourtney** [comment]
@hannesm thanks, but passing `--net socket` as per above resolves the permission issue, so that works fine without sudo. For the ukvm case I see that `--net` is an arg that was missing from the docs, it boots and says its on 10.0.0.2 but I can't ping/curl that from localhost

**Comment by hannesm** [comment]
@ciarancourtney ic.  on your host system, you'll need an IP address in the same subnet... some `ifconfig tap0 10.0.0.1 netmask 255.255.255.0` should do the trick (and then `ping 10.0.0.2` should work).

**Comment by yomimono** [comment]
@ciarancourtney I'm closing this issue, but please do reopen it and let us know more if you're still having difficulty getting the networking examples running.
