### ISSUE TITLE
building the lwt tracing branch fails

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-skeleton#237]
See https://travis-ci.org/mirage/mirage-skeleton/jobs/279166950#L1237 .

I'm in the middle of a few other things and don't have time to look into this - @talex5 , maybe you'll get to it first?

**Comment by talex5** [comment]
Indeed. The `mirage/lwt#tracing` branch no longer builds, with:

```
ocamlfind: Package `cppo_ocamlbuild' not found
```

I've made a PR (https://github.com/mirage/lwt/pull/16) and added a monthly Travis cron job to check it.

**Comment by yomimono** [comment]
Thanks, @talex5 !

**Comment by olleolleolle** [comment]
@yomimono The Travis build is now green on `master`. Does that "fix" this issue (can we close this now?)?

**Comment by yomimono** [comment]
Yes!  Thanks, @olleolleolle !
