### ISSUE TITLE
Evaluation of Unikernels

### ISSUE THREAD

**Issue by marqueswsm** [mirage/mirage-skeleton#238]
Hello. I'm working with Mirage OS and am hosting the unikernels on a local Xen server. However, unikernels are with performing poorly. The throughput is around 30 kbps and conventional virtual machines at 500 kbps. I thought I had some configuration problem but I found a scientific paper that according to Briggs et al. (2015), **during testing of the Mirage HTTP server we encountered a severe bug: the Mirage TCP / IP library apparently leaks memory every time a TCP connection is released, on the order of 30 kilobytes per TCP connection. We have filed a bug with the Mirage OS authors. Unfortunately, this causes the performance of Mirage to be very poor; we expect this performance would be greatly improved after this bug is fixed.**

This problem has already been solved and how should I proceed?

Reference.
BRIGGS, Ian et al. A performance evaluation of unikernels. 2015.

-- I apologize for possible grammatical errors, English is not my native language.

**Comment by yomimono** [comment]
Hi @wagnersmarques1 , can you tell us more about how you're evaluating the throughput of the unikernel?  We don't really have enough information to help you proceed further.

**Comment by wagnersmarques1** [comment]
Of course, @yomimono. And I've evaluated the throughput of mirage on the xen hypervisor. I've compiled static_website_tls contained in this repository for xen. I installed the unikernel with the command **xl create https.xl** and informing the configured bridge in xen. Then I checked his performance against the various quantities of requests using Apache Benchmark and Siege. However, the throughput is no more than 30 kbps. I've set up a load balancer too (Nginx and Haproxy) but the results have not improved. Using a traditional VM the throughput is 1000 kbps or more.

**Comment by talex5** [comment]
I don't know if this will help, but there are some articles about profiling a cohttp unikernel here:

- http://roscidus.com/blog/blog/2014/08/15/optimising-the-unikernel/
- http://roscidus.com/blog/blog/2014/10/27/visualising-an-asynchronous-monad/

which got `7.24 MB/s` from an ARM board running Xen. I don't know what kind of requests your tests do though - even 1000 kbps sounds very slow!

**Comment by hannesm** [comment]
Thanks for your report! The last comment is some years old, but we're hugely interested in performance and spotting the bottlenecks. Unfortunately this repository is the wrong one for such issues/reports since it does not contain network code (only the raw unikernels) -- e.g. https://github.com/mirage/qubes-mirage-firewall/ is better suited) -- also more recent changes (such as https://github.com/mirage/mirage/pull/968) improved the performance already. Maybe the https://github.com/TImada/mirage_iperf/ unikernels are a nice initial benchmark?
