### ISSUE TITLE
static_website_tls does not respond on Mac

### ISSUE THREAD

**Issue by Thegaram** [mirage/mirage-skeleton#254]
I am trying to run the `static_website_tls` example on my Mac. The build complains about some dependencies (that I have in fact installed), but then succeeds if I run the commands manually. The applications seems to run fine, but I cannot connect to it, i.e. it doesn't respond to my requests.

```
$ mirage configure -t macosx
$ make depend
opam pin add --no-action --yes mirage-unikernel-https-macosx .
Package mirage-unikernel-https-macosx does not exist, create as a NEW package ? [Y/n] y
[mirage-unikernel-https-macosx.~dev] synchronised from file:///Users/thegaram/Documents/work/learn/mirage-skeleton/applications/static_website_tls
[NOTE] Converting format of /Users/thegaram/.opam/default/.opam-switch/sources/mirage-unikernel-https-macosx/mirage-unikernel-https-macosx.opam from 1.2 to 2.0~beta5
[WARNING] Failed checks on mirage-unikernel-https-macosx package definition from source at
          file:///Users/thegaram/Documents/work/learn/mirage-skeleton/applications/static_website_tls:
    error 23: Missing field 'maintainer'
    error 25: Missing field 'authors'
    error 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
mirage-unikernel-https-macosx is now pinned to file:///Users/thegaram/Documents/work/learn/mirage-skeleton/applications/static_website_tls (version ~dev)
opam depext --yes --update mirage-unikernel-https-macosx
# Detecting depexts using vars: arch=x86_64, os=macos, os-distribution=homebrew, os-family=macos
# The following system packages are needed:
autoconf
gmp
Skipping system update on this platform.
# OS package update successful
Sorry, don't know how to install packages on your macos system
make: *** [depend] Error 1

$ opam install --yes --deps-only mirage-unikernel-https-macosx
...

$ make
...
ld: warning: directory not found for option '-L/opt/local/lib'

$ ./https
2018-02-26 09:43:08 +01:00: ERR [application] main: Lwt_vmnet.Permission_denied
Raised at file "lib/vmnet.ml", line 99, characters 9-32
Called from file "lib/lwt_vmnet.ml", line 62, characters 14-33
Called from file "src/core/lwt.ml", line 2036, characters 16-20

$ sudo ./https 
Password:
2018-02-26 09:43:19 +01:00: INF [net-macosx] Netif: connect unknown
2018-02-26 09:43:19 +01:00: INF [ethif] Connected Ethernet interface 0a:49:f5:e4:0c:46
2018-02-26 09:43:19 +01:00: INF [arpv4] Connected arpv4 device on 0a:49:f5:e4:0c:46
2018-02-26 09:43:19 +01:00: INF [udp] UDP interface connected on 10.0.0.2
2018-02-26 09:43:19 +01:00: INF [tcpip-stack-direct] stack assembled: mac=0a:49:f5:e4:0c:46,ip=10.0.0.2
2018-02-26 09:43:19 +01:00: INF [https] listening on 4568/TCP
2018-02-26 09:43:19 +01:00: INF [http] listening on 8081/TCP
2018-02-26 09:45:19 +01:00: INF [arpv4] ARP: timeout 192.168.64.1
2018-02-26 09:45:19 +01:00: INF [arpv4] ARP: timeout 192.168.64.1

```

I tried reaching the server both using `localhost` and `10.0.0.2` (using ports `4568` and `8081`) but there's no response. I am not sure what the Netif thing and the ARP timeouts mean. If I check the given ports, it seems like no process is listening on them:

```
$ lsof -n -i4TCP:4568 | grep LISTEN
$ lsof -n -i4TCP:8081 | grep LISTEN
```

What am I missing? Any help is appreciated!

**Comment by Thegaram** [comment]
Just found out it works if I use

```
$ mirage configure -t macosx --net socket
```

Is this the correct usage? If yes, it might be a good idea to update the instructions in the README file (I can create a PR for this).

**Comment by hannesm** [comment]
Dear @Thegaram, to run `static_website_tls` on Unix/MacOSX, you have two possibilities how to deal with networking:
- use the Unix sockets API (`--net socket`)
- use the MirageOS TCP/IP stack and a tun/tap interface (which is a virtual layer 2 network device).

If you select the latter, MirageOS uses by default `10.0.0.2/24` (with the router being `10.0.0.1`).  This means, you must configure the other end of the tap device as `10.0.0.1` - should be as simple as `ifconfig tap0 10.0.0.1/24` (or connect this tap device to a (virtual) bridge interface). You seem to use the 192.168.64.1 network instead (and can use `mirage configure --ipv4=192.168.42.2/24 --ipv4-gateway=192.168.42.1` to configure the unikernel to use the other ip -- this configuration can also be done at startup time (by passing the arguments as command-line parameters).

**Comment by Thegaram** [comment]
Thanks for the prompt reply @hannesm! It's all clear now. I'll close the issue.

**Comment by yomimono** [comment]
There is an additional problem when running on MacOSX with the MirageOS TCP/IP stack: the network driver used there will not work with a static IPv4 configuration and needs to be configured over DHCP.  See [the readme for mirage-net-macosx](https://github.com/mirage/mirage-net-macosx#limitations) and [the original issue](https://github.com/mirage/mirage-net-macosx/issues/3) for slightly more information.
