### ISSUE TITLE
[aarch64] problem building the static_website_tls

### ISSUE THREAD

**Issue by bchalios** [mirage/mirage-skeleton#259]
Hi all,

I have a problem building the static_website_tls package when configuring for the ``ukvm`` target. I am working on an aarch64 board.

This is what I run: 

``bchalios@hikey970:~/mnt/repos/mirage/mirage-skeleton/applications/static_website_tls$ mirage configure -t ukvm``
``bchalios@hikey970:~/mnt/repos/mirage/mirage-skeleton/applications/static_website_tls$ make depend``

And here is the output:

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[mirage-unikernel-https-ukvm] /home/bchalios/mnt/repos/mirage/mirage-skeleton/applications/static_website_tls/ already up-to-date
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
Makefile:12: recipe for target 'depend' failed
make: *** [depend] Error 3

I don't have a problem building other packages of mirage-skeleton (even though I haven't yet tried all of them)

Thanks!

**Comment by hannesm** [comment]
which opam version do you use (could you paste the output of `opam config report`)?  do you have `aspcud` installed?  which OCaml version do you use?

**Comment by bchalios** [comment]
Thanks for your answer!

Here's the output of opam config report

bchalios@hikey970:~/mnt/repos/mirage/mirage-skeleton/applications/static_website_tls$ opam config report
\# OPAM config report
\# opam-version    1.2.2 
\# self-upgrade    no
\# os              linux
\# external-solver aspcud $in $out $criteria
\# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
\# jobs            4
\# repositories    1* (http)
\# pinned          1 (path)
\# current-switch  4.04.2
\# last-update     2018-08-04 17:49_

and ocaml version:

bchalios@hikey970:~/mnt/repos/mirage/mirage-skeleton/applications/static_website_tls$ ocaml --version
The OCaml toplevel, version 4.04.2

and yes, aspcud is installed.

**Comment by mato** [comment]
This is normal, but the error is confusing as OPAM 1.x is really bad at telling you what dependency cannot be installed.

The error is due to missing support for `aarch64` in `mirage-entropy`, see https://github.com/mirage/mirage-entropy/issues/38. Until that is fixed, you will not be able to build anything that depends on it on `aarch64`.

The examples in mirage-skeleton that do not require this dependency, such as `device-usage/network` should work fine.

**Comment by mato** [comment]
@hannesm I'm not the original reporter, but `static_website_tls` works fine for me on `aarch64` with the new mirage-entropy.

**Comment by hannesm** [comment]
@mato thanks, @bchalios I'm closing this issue, please re-open if you still have issues getting the example to work on aarch64
