### ISSUE TITLE
HTTP_Fetch Example Hangs when run as a Unikernel on Solo 5

### ISSUE THREAD

**Issue by cm16161** [mirage/mirage-skeleton#287]
I found that the tutorial example works when used on a UNIX machine when generated with ```mirage configure -t unix``` command, but when compiling into a Solo5 unikernel with ```mirage configure -t hvt``` the resulting executable does not perform correctly.
I suspect that this has something to do with the fact that it is not setup to use a direct network rather than a socket. 
 
```
$ solo5-hvt --net:service=tap100 http_fetch.hvt
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Bindings version v0.6.4
Solo5: Memory map: 512 MB addressable:
Solo5:   reserved @ (0x0 - 0xfffff)
Solo5:       text @ (0x100000 - 0x3d8fff)
Solo5:     rodata @ (0x3d9000 - 0x45afff)
Solo5:       data @ (0x45b000 - 0x61afff)
Solo5:       heap >= 0x61b000 < stack < 0x20000000
2020-03-27 15:31:33 -00:00: INF [netif] Plugging into service with mac ee:a9:b2:8c:65:bc mtu 1500
2020-03-27 15:31:33 -00:00: INF [ethernet] Connected Ethernet interface ee:a9:b2:8c:65:bc
2020-03-27 15:31:33 -00:00: INF [ARP] Sending gratuitous ARP for 10.0.0.2 (ee:a9:b2:8c:65:bc)
2020-03-27 15:31:33 -00:00: INF [udp] UDP interface connected on 10.0.0.2
2020-03-27 15:31:33 -00:00: INF [tcpip-stack-direct] stack assembled: mac=ee:a9:b2:8c:65:bc,ip=10.0.0.2
Resolving using DNS server 91.239.100.100
Fetching http://mirage.io with Cohttp:
2020-03-27 15:33:06 -00:00: ERR [dns_client_mirage] error connecting to nameserver connection attempt timed out
Fatal error: exception (Failure "name resolution failed: connect failure: unknown endpoint type")

```

**Comment by hannesm** [comment]
thanks for your bug report. is the tap interface you connect the unikernel to (tap100) setup to have its traffic routed (& NAT) to the outside world? how is your `-t unix` setup, do you use the host socket stack or a tap interface as well?

**Comment by cm16161** [comment]
tap100 is setup using the instructions given by the Solo5 team:
``` 
ip tuntap add tap100 mode tap
ip addr add 10.0.0.1/24 dev tap100
ip link set dev tap100 up
```
Regarding how ```-t unix``` is setup, I don't know, I was simply following the tutorials using the commands provided and found this bug.
```
$ mirage --version
v3.7.6
$ opam --version
2.0.4

$ ocaml --version 
The OCaml toplevel, version 4.10.0
``` 
I am using Ubuntu LTS 18.04 but have installed a newer version of OCaml and Opam to resolve dependency issues when running the tutorial examples

**Comment by hannesm** [comment]
ok, cool. The setup of your tap interface won't give your virtual machine / unikernel any access to the outside world. You will need on your host system to run a firewall/network address translation/forward IP packets via your uplink, so that your unikernel can communicate with the Internet.

If you're using linux and iptables, [this guide](https://www.revsys.com/writings/quicktips/nat.html) may be helpful (copy & pasted the instructions from there):
```bash
$ echo 1 > /proc/sys/net/ipv4/ip_forward # enables IP forwarding

# assuming "eth0" is your default network interface where all the traffic goes to the Internet.
$ /sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
$ /sbin/iptables -A FORWARD -i eth0 -o tap100 -m state --state RELATED,ESTABLISHED -j ACCEPT
$ /sbin/iptables -A FORWARD -i tap100 -o eth0 -j ACCEPT
```

**Comment by cm16161** [comment]
Bingo it worked! 
Thank you so much :smiley: :+1:
