### ISSUE TITLE
The noop and hello examples don’t build without changes

### ISSUE THREAD

**Issue by schubev** [mirage/mirage-skeleton#342]
I am following the [Hello MirageOS World](https://mirage.io/docs/hello-world) tutorial and I notice that I can’t build (at least) the noop and hello examples without changes. Namely, it seems the `Mirage.main` value doesn’t exist. By seeing what exists in Mirage and what matches the expected types I found that `Mirage.foreign` seems to have replaced `Mirage.main`? Can you please confirm this is accurate? If so I’ll be happy to submit a PR to use `Mirage.foreign` instead, and also I would update https://github.com/mirage/mirage-www/blob/master/data/wiki/hello-world.md.

I think my environment is mostly up to date, but just in case:
```
$ mirage --version
v3.10.8

$ opam --version
2.0.8

$ ocaml --version
The OCaml toplevel, version 4.13.1
```

**Comment by hannesm** [comment]
With the recent release of MirageOS 4.0 (see e.g. https://mirage.io/blog/announcing-mirage-40), the examples were updated. You'll need opam >=2.1 and mirage >= 4 to get them working. Otherwise, you can use the `mirage-3` branch on this repository which should work with MirageOS 3.x.

**Comment by schubev** [comment]
Oh my bad then. Thanks a lot!
