### ISSUE TITLE
Missing RE dependency for xen/static_website+ip 

### ISSUE THREAD

**Issue by voila** [mirage/mirage-skeleton#46]
was previously fixed in static_website, see:
 
https://github.com/mirage/mirage-skeleton/commit/fe32f34c2411b80856e39884782f70c8a359b247

**Comment by djs55** [comment]
I tried this with d2500bf633206a88bac6c72b2ac2864341ff1f60 and mirage-2.7.0 and it linked ok (with `re.str`). Reopen if you still see this!
