### ISSUE TITLE
Linking problem when compiling the xen version of unikernel with networking

### ISSUE THREAD

**Issue by philtomson** [mirage/mirage-skeleton#49]
Following the Hello World instructions section 3 Networking, from here: http://openmirage.org/wiki/hello-world

I'm running this on a cubieboard2 using the prebuilt cubieboard2.img (downloaded today).

Running the stackv4 example:

    $ mirage configure --xen
    $ make

I get this in the linking phase:
ld -d -static -nostdlib --start-group \
	  $(pkg-config --static --libs openlibm 'libminios-xen >= 0.2') \
	  _build/main.native.o /home/mirage/.opam/system/lib/mirage-xen/libocaml.a \
	  /home/mirage/.opam/system/lib/mirage-xen/libxencaml.a --end-group \
	  -L/usr/lib/ocaml \
	  -lbigarray \
	  -L/home/mirage/.opam/system/lib/cstruct \
	  -lcstruct_stubs \
	  -L/home/mirage/.opam/system/lib/shared-memory-ring \
	  -lshared_memory_ring_stubs \
	  -L/home/mirage/.opam/system/lib/lwt \
	  -llwt-unix_stubs \
	  -lpthread \
	  -L/home/mirage/.opam/system/lib/ssl \
	  -lssl_stubs \
	  -lcrypto \
	  -lssl \
	  -L/home/mirage/.opam/system/lib/tcpip \
	  -ltcpip_stubs \
	  /usr/lib/gcc/arm-linux-gnueabihf/4.8/libgcc.a \
	  -o mir-stackv4.elf
ld: cannot find -lpthread
ld: cannot find -lcrypto
ld: cannot find -lssl
make: *** [build] Error 1

So it looks like you I'm supposed to have alternate libpthread, libcrypto and libssl libs in /home/mirage/opam/system/lib/(tcpip,ssl,lwt) but I do not see these. How would those have been created? Did I miss a step somewhere?  I was able to get the simple hello world xen version working (the one without networking)

**Comment by djs55** [comment]
I think the linking problem is fixed in mirage-2.7.0. I successfully cloned mirage-skeleton and ran
```
mirage configure --xen --dhcp true
make
```
in the stackv4 example. Reopen if this is still a problem!
