### ISSUE TITLE
static_website fails to configure

### ISSUE THREAD

**Issue by bbrietzke** [mirage/mirage-skeleton#53]
I recently checked out the mirage  skeleton project, and when i try to run the ``static_website` example, I'm greeted with the following:

**mirage configure**
Mirage      Using scanned config file: config.ml
Mirage      Processing: /Users/bbrietzke/Development/mirage-skeleton/static_website/config.ml
Mirage      => rm -rf /Users/bbrietzke/Development/mirage-skeleton/static_website/_build/config.*
Mirage      => cd /Users/bbrietzke/Development/mirage-skeleton/static_website && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs
Mirage       ocamlfind ocamldep -package mirage -modules config.ml > config.ml.depends
Mirage       ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
Mirage       + ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
Mirage       File "config.ml", line 41, characters 2-16:
Mirage       Error: Unbound value conduit_direct
Mirage       Command exited with code 2.
[ERROR]      The command "cd /Users/bbrietzke/Development/mirage-skeleton/static_website && ocamlbuild -use-ocamlfind -tags annot,bin_annot -pkg mirage config.cmxs" exited with code 10.

I am able to run the `console` example without an issue.

I've deleted my `~/.opam` directory and reinstalled everything and still came back with the same results.

I have run this on both an clean OS/X & Ubuntu machines with the same results.

Let me know what additional information or troubleshooting I can do to help. 

The install modules on my system:

**opam list**
Installed packages for system:
base-bigarray             base  Bigarray library distributed with the OCaml compiler
base-bytes              legacy  Bytes compatibility library distributed with ocamlfind
base-no-ppx               base  A pseudo-library to indicate lack of extension points support
base-threads              base  Threads library distributed with the OCaml compiler
base-unix                 base  Unix library distributed with the OCaml compiler
bin_prot             111.03.00  A binary protocol generator
camlp4                  4.01.0  Camlp4 is a system for writing extensible parsers for programming languages
cmdliner                 0.9.5  Declarative definition of command line interfaces for OCaml
cohttp                  0.11.2  HTTP library for Lwt, Async and Mirage
comparelib           109.60.00  Part of Jane Street’s Core library
conduit                  0.5.1  Network connection library for TCP and SSL
core                 111.28.00  Industrial strength alternative to OCaml's standard library
core_kernel          111.28.00  Industrial strength alternative to OCaml's standard library
cstruct                  1.4.0  access C structures via a camlp4 extension
custom_printf        111.25.00  Extension for printf format strings
enumerate            111.08.00  Quotation expanders for enumerating finite types.
fieldslib            109.20.03  Syntax extension to define first class values representing record fields, to get and set record fields, iterate and fold over
herelib              109.35.02  Part of Jane Street’s Core library
io-page                  1.1.1  Allocate memory pages suitable for aligned I/O
ipaddr                   2.5.0  IP (and MAC) address representation library
lwt                      2.4.6  A cooperative threads library for OCaml
mirage                   1.2.0  The Mirage library operating system
mirage-clock-unix        1.0.0  A Mirage-compatible Clock library for Unix
mirage-console-unix      1.0.0  A Mirage-compatible Console library for Unix
mirage-http              1.1.0  Mirage HTTP client and server driver for Unix
mirage-net-unix          1.1.1  Ethernet network driver for Mirage, using tuntap
mirage-types             1.2.0  Module type definitions for Mirage-compatible applications
mirage-unix              1.1.0  Mirage OS library for Unix compilation
ocamlfind                1.5.3  A library manager for OCaml
ocplib-endian              0.7  Optimised functions to read and write int16/32/64 from strings and bigarrays, based on new primitives added in version 4.01.
optcomp                    1.6  Optional compilation with cpp-like directives
ounit                    2.0.0  Unit testing framework loosely based on HUnit. It is similar to JUnit, and other XUnit testing frameworks
pa_bench             111.28.00  Syntax extension for inline benchmarks
pa_ounit             111.28.00  Syntax extension for oUnit
pa_test              111.08.00  Quotation expander for assertions.
pipebang             110.01.00  Part of Jane Street’s Core library
re                       1.2.2  RE is a regular expression library for OCaml
sexplib              111.25.00  Library for serializing OCaml values to and from S-expressions
shared-memory-ring       1.1.0  Shared memory rings for RPC and bytestream communications.
ssl                      0.4.7  Bindings for OpenSSL
stringext                1.0.0  Extra string functions for OCaml
tcpip                    1.1.6  Userlevel TCP/IP stack
tuntap                   1.0.0  TUN/TAP bindings
type_conv            111.13.00  Library for building type-driven syntax extensions
typerep              111.17.00  typerep is a library for runtime types.
uri                      1.7.2  RFC3986 URI/URL parsing library
variantslib          109.15.03  Part of Jane Street’s Core library

**Comment by djs55** [comment]
I successfully tried `static_website`, `conduit_server` and `conduit_server_manual` with a clean opam with mirage 2.4.0 on Ubuntu 14.04. I suspect the problem you suffered has been fixed in a recent release. Please re-open if it still doesn't work!
