### ISSUE TITLE
update DNS example to use dns_server_mirage

### ISSUE THREAD

**Issue by heidihoward** [mirage/mirage-skeleton#81]
I believe that as of https://github.com/mirage/ocaml-dns/pull/55, we can simplify the dns example as some of this functionality has been moved to Dns_server_mirage. This needs to wait until 0.15.0 release of ocaml-dns

feel free to assign me to do fix this issue

**Comment by dsheets** [comment]
`dns.0.15.0` was released as ocaml/opam-repository#4092 .

**Comment by djs55** [comment]
@heidi-ann thanks for the offer! If you still have time, could you give it a shot?

**Comment by yomimono** [comment]
I suspect the offer to take care of this is no longer valid, but (I think) the suggestion still is, despite a large amount of code churn since this was initially filed.

**Comment by heidi-ann** [comment]
would probably be best if someone more familiar with the codebase handles it, it's been a few years while since I last looked at this

**Comment by hannesm** [comment]
Superseeded by further ocaml-dns development (4.x is out now) - and available servers (see https://mirage.io/wiki/gallery for our supported unikernels).
