### ISSUE TITLE
Inconsistencies with documentation

### ISSUE THREAD

**Issue by mor1** [mirage/mirage-skeleton#97]
At least some examples are out-of-date (at least `stackv4`) with respect to the `wiki/hello-world` documentation.

All samples should be checked through on a release to make sure they're current, and to make sure documentation is up-to-date.

**Comment by mor1** [comment]
@dongcarl
 
Per email conversation a couple of days ago, I've started fixing this; see mirage/mirage-www#370 and mirage/mirage-skeleton#98.

Still working through changes in the way the direct network stack is accessed on OSX, and building VM to check on Linux.

But if you could comment on whether what's there so far makes sense, that'd be really useful!

**Comment by hannesm** [comment]
I think this can be closed.. @mor1?

**Comment by mor1** [comment]
Agree, closing.
